### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [nrabbi/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by nrabbi** [comment]
i added this line to the head of applicationlayout view

<meta name=viewport content = "width=device-width, initial-scale=1">

is that what you wanted?

**Comment by BillyMassey** [comment]
Perfect! Way to go 👍
